name: Azure Pipelines

trigger:
- main
pool: myPool

variables:
  python.version: '3.7.6'
  azureServiceConnectionId: 'a3a7c26e-4d37-405c-91fb-89548a312d92'
  projectRoot: $(System.DefaultWorkingDirectory)
  environmentName: 'test'
  serviceConnection: 'a3a7c26e-4d37-405c-91fb-89548a312d92'


stages:
#--------------------------------------------#  
# BUILD STAGE
#--------------------------------------------#    
- stage: Build
  jobs:
  - job: BuildInfrastructure
    steps:
      - task: TerraformInstaller@0
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: '0.13.5'
      
      - task: TerraformInstaller@0
        displayName: 'Terraform Init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
          backendServiceArm: '$(terraformServiceConnection)'
          backendAzureRmResourceGroupName: '$(terraformstoragerg)'
          backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
          backendAzureRmContainerName: '$(terraformcontainer)'
          backendAzureRmKey: 'terraform.tfstate'
          terraformVersion: '0.13.5'

      - task: TerraformInstaller@0
        displayName: 'Terraform Apply'
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
          commandOptions: '-auto-approve -var="public_key=$(myPublicKey))"'
          environmentServiceNameAzureRM: '$(terraformServiceConnection)'

      - task: ArchiveFiles@2
        displayName: 'Archive FakeRestAPI Web App'
        inputs:
          rootFolderOrFile: 'automatedtesting/jmeter/fakerestapi'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'

      - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
        displayName: 'Upload Fakerestapi Package'
        artifact: drop-fakerestapi
      - task: ArchiveFiles@2
        displayName: 'Archive Selenium Tests'
        inputs:
          rootFolderOrFile: 'automatedtesting/selenium'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-selenium.zip'
      - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-selenium.zip
        displayName: 'Upload Selenium Package'
        artifact: selenium

- stage: Deploy
  jobs:
  - deployment: FakeRestAPI
    displayName: 'Deploy Web App to APP Service'
    pool: myPool
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy CodingAPP to App Service'
            inputs:
              azureSubscription: '$(serviceConnection)'
              appName: 'fakeapiappkaizen'
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip